version: '3'
services: 
  web:
    network_mode: host
    image: "node:8"
    working_dir: '/app'
    volumes:
      - .:/app
    ports: : 
      - '8082:8080'
    command: >
      bash -c "npm install express 
      && node index.js"