version: '3'
services: 
  web:
    image: "node:8"
    working_dir: '/app'
    volumes:
      - .:/app
    expose: 
      - '8080'
    command: >
      bash -c "npm install express 
      && node index.js"